services:
  api:
    build: API_HealthGuard/.
    restart: always 
    ports: "8000:8000" 
    environment: 
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
    command: bash -c "/opt/venv/bin/python diabete.py"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - healthguard_network

  db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql:ro
    networks:
      - healthguard_network

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "5000:8080"
    depends_on:
      - db
    networks:  
      - healthguard_network

volumes:
  postgres_data:

networks:
  healthguard_network: 
    driver: bridge
