name: build

on:
  push:
    branches: [ "main","feature/build" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-react:
      name: Build React Project
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: HealGuard
        run: npm install

      - name: Build React app
        working-directory: HealGuard
        run: npm run build:web


